trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release/*
  paths:
    exclude:
      - README.md

variables:
  build: $(Build.BuildId)
  GOROOT: '/usr/local/go1.12' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  ref: $(Build.SourceBranch)
  branch: $(Build.SourceBranchName)
  version:

jobs:
  - job: CLI
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:

      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 2.5.1'
          addToPath: true
        displayName: 'Install Ruby'

      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: 'github.com,192.30.255.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDe6oGmJeWmvXRj9dWJmI2XtWmhrClTmnqfKK3ohF5+OhB+c3O7hLIlTfiRQVlGVKu3dUGP+woybJ77eau0OpPKTirZhLct+tsbSNTc5NEyOmeUDVn9AfKj748NGEi9gAJ9PfjbpTo5hakLdDSGbG3HNmt75B7oOpx0SpxnGQZGJOkxYw66OYpWrCGcUB7nuqporM16AOEKVbvayYgXw5Pi7xql++VOHdmniaMStdJyjBZFyIpD+oxvUhwpJ+FthlknDk2p0BQImLsF+h3g7ZFYTlSY3y/v/2k4bY9NRUF3Xdgd3FsyF712cfONgPdxnKQLJkyRArUrqHM8lCeg70Lz serge@Serges-MacBook-Pro.local'
          sshKeySecureFile: id_rsa

      - script: |
          if [[ $(ref) == refs/heads/release* ]]; then
            RCVERS=$(echo $(ref) | sed "s|refs/heads/release/||g")
            echo "##vso[task.setvariable variable=version]$RCVERS-b$(build)"
          elif [[ $(ref) == refs/tags* ]]; then
            TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
            echo "##vso[task.setvariable variable=version]$TAG"
          else
            LATESTTAG=$(git tag | tail -1)
            LATESTVERS=${LATESTTAG#?}
            if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
            echo "##vso[task.setvariable variable=version]$LATESTVERS-b$(build)"
          fi
          echo $(version)
        displayName: 'Set version variable'

      - script: |
          mkdir -p '$(GOBIN)'
          mkdir -p '$(GOPATH)/pkg'
          mkdir -p '$(modulePath)'
          shopt -s extglob
          mv !(gopath) '$(modulePath)'
          echo '##vso[task.prependpath]$(GOBIN)'
          echo '##vso[task.prependpath]$(GOROOT)/bin'
        displayName: 'Set up the Go workspace'

      - task: GoTool@0
        inputs:
          version: '1.12.1'
          goPath: $(GOPATH)
          goBin: $(GOBIN)
        displayName: 'Install Golang'
      
      - script: |
          ./script/check_fmt.sh
        workingDirectory: '$(modulePath)'
        displayName: 'Check Source Format'

      - script: |
          script/bootstrap.sh
        workingDirectory: '$(modulePath)'
        displayName: 'Bootstrap'

      - script: |
          make dep
          make test
          pwd
          ls -l
        workingDirectory: '$(modulePath)'
        displayName: 'Run Tests'

      # Publish Test Results
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
        displayName: 'Publish Test Results'
      
      - script: |
          BRANCH=$(branch) GOOS=darwin VERSION=$(version) make build
          tar -zcf iofogctl.tar.gz bin/iofogctl
          checksum=$(shasum -a 256 iofogctl.tar.gz | awk '{ print $1 }')
          cp iofogctl.tar.gz $(Build.ArtifactStagingDirectory)
          echo $(version) > $(Build.ArtifactStagingDirectory)/version.txt
          rsync -e "ssh -o StrictHostKeyChecking=no" iofogctl.tar.gz root@104.130.140.232:/var/www/vhosts/edgeworx.io/downloads/iofogctl/dev/$(version).tar.gz
          git config --global user.email "serge@edgeworx.io"
          git config --global user.name "Serge Radinovich"
          git clone git@github.com:eclipse-iofog/homebrew-iofogctl.git
          cd homebrew-iofogctl
          sed -i "s/    sha256.*/    sha256 \"$checksum\"/g" iofogctl.rb
          sed -i "s/    version.*/    version \"$(version)\"/g" iofogctl.rb
          sed -i "s|http://edgeworx.io/downloads/iofogctl/dev/.*\.tar\.gz\"|http://edgeworx.io/downloads/iofogctl/dev/$(version).tar.gz\"|g" iofogctl.rb
          git add iofogctl.rb
          git commit -m "Publish develop version $(version)"
          git push origin master
        workingDirectory: '$(modulePath)'
        displayName: 'Build and publish OSX binary'

      - script: |
          BRANCH=$(branch) VERSION=$(version) make build
          GOPATH=$(GOPATH) GOBIN=$(GOBIN) sudo make install
        workingDirectory: '$(modulePath)'
        displayName: 'Build and Install Linux version'

      - script: |
          which iofogctl
          iofogctl version
        displayName: 'Verify Install'

      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'package_cloud'
        displayName: 'Download package cloud token file'

      - script: |
          gem install fpm
          fpm -h
          gem install package_cloud
          package_cloud -h
          echo "config file..."
          echo $DOWNLOADSECUREFILE_SECUREFILEPATH
        displayName: 'Install package_cloud cli and fpm'

      - script: |
          fpm -f -s dir -t deb -n iofogctl -v $(version) /usr/local/bin/iofogctl=/usr/local/bin/
          package=$(ls | grep *.deb)
          echo $package
          cp $package $(Build.ArtifactStagingDirectory)
        displayName: 'Create Debian package'

      - script: |
          package=$(ls | grep *.deb)
          echo "package..."
          echo $package
          declare -a UBUNTU_VERS=("precise" "trusty" "utopic" "vivid" "wily" "xenial" "bionic")
          declare -a DEBIAN_VERS=("wheezy" "jessie" "stretch" "buster")
          for ubu in "${UBUNTU_VERS[@]}"
          do
              package_cloud push iofog/iofogctl-snapshots/ubuntu/${ubu} $package --config=$DOWNLOADSECUREFILE_SECUREFILEPATH
          done
          for deb in "${DEBIAN_VERS[@]}"
          do
              package_cloud push iofog/iofogctl-snapshots/debian/${deb} $package --config=$DOWNLOADSECUREFILE_SECUREFILEPATH
              package_cloud push iofog/iofogctl-snapshots/raspbian/${deb} $package --config=$DOWNLOADSECUREFILE_SECUREFILEPATH
          done
        displayName: 'Publish deb to package-cloud'

      - script: |
          fpm -f -s dir -t rpm -n iofogctl -v $(version) /usr/local/bin/iofogctl=/usr/local/bin/
          package=$(ls | grep *.rpm)
          echo $package
          cp $package $(Build.ArtifactStagingDirectory)
        displayName: 'Create RPM package'

      - script: |
          package=$(ls | grep *.rpm)
          echo "package..."
          echo $package
          declare -a FEDORA_VERS=("22" "23" "24")
          declare -a REDHAT_VERS=("6" "7")
          for fed in ${FEDORA_VERS[@]}
          do
              package_cloud push iofog/iofogctl-snapshots/fedora/${fed} $package --config=$DOWNLOADSECUREFILE_SECUREFILEPATH
          done
          for red in ${REDHAT_VERS[@]}
          do
              package_cloud push iofog/iofogctl-snapshots/el/${red} $package --config=$DOWNLOADSECUREFILE_SECUREFILEPATH
          done
        displayName: 'Publish RPM to package-cloud'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'iofogctl'
        displayName: 'Publish artefacts'